name: neil

on:
  push:
    branches: ["master"]

jobs:
  qualidade:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-26.04]
        python-version: ["3.12", "3.11", "3.10"]
    runs-on: ${{ matrix.os }}

    steps: 
      - name: Preparar Ambiente
        uses: actions/checkout@v4

      - name: Configurar python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Instalar dependências
        run:  pip install -r requirements.txt

      - name: Linter Flake8
        run: flake8 .

      - name: Executar testes unitarios
        run: pytest testes.py -v

      - name: Verificar cobertura de codigo
        run: pytest testes.py --cov=. --cov-fail-under=85

      - name: Analise de Seguranca
        run: bandit -r . -x ./testes.py

      - name: Verificar Chaves expostas
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Analise com SonarQube
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}